[program:mc]
priority=100
command=python3 mc.py --use-console --log-level DEBUG --pipe
directory=/home/shaul/open-nano-dlp
autostart=true
autorestart=unexpected
exitcodes=3
stopsignal=INT
user=shaul
stderr_logfile=/var/log/supervisor/mc.err.log
stderr_logfile_maxbytes=30MB
stderr_logfile_backups=4
stdout_logfile=/var/log/supervisor/mc.out.log
stdout_logfile_maxbytes=30MB
stdout_logfile_backups=4
# See sygsegv.cpp. The signal handler prints to stderr, so we need to log stderr to syslog.
stderr_syslog=true