[program:pigpiod]
priority=100
command=pigpiod -g
directory=/home/shaul/open-nano-dlp
autostart=true
autorestart=unexpected
exitcodes=3
stopsignal=INT
user=root
stderr_logfile=/var/log/supervisor/pigpiod.err.log
stderr_logfile_maxbytes=30MB
stderr_logfile_backups=4
stdout_logfile=/var/log/supervisor/pigpiod.out.log
stdout_logfile_maxbytes=30MB
stdout_logfile_backups=4
# See sygsegv.cpp. The signal handler prints to stderr, so we need to log stderr to syslog.
stderr_syslog=true